FROM python:3.6

ENV PYTHONIOENCODING "utf-8"

RUN apt-get update \
  && apt-get install -y mecab \
  && apt-get install -y libmecab-dev \
  && apt-get install -y mecab-ipadic-utf8 \
  && apt-get install -y git \
  && apt-get install -y make \
  && apt-get install -y curl \
  && apt-get install -y xz-utils \
  && apt-get install -y file \
  && apt-get install -y sudo \
  && apt-get install -y wget \
  && apt-get install -y default-libmysqlclient-dev

RUN git clone --depth 1 https://github.com/neologd/mecab-ipadic-neologd.git\
    && cd mecab-ipadic-neologd\
    && bin/install-mecab-ipadic-neologd -n -y

ADD . /src/
WORKDIR /src/
RUN pip install -r requirements.txt

ENV TZ Azia/Tokyo
ENV FLASK_APP run.py
ENV FLASK_ENV development

EXPOSE 5000

CMD flask run --host 0.0.0.0 --port 5000